name: Bug report
description: Report a reproducible problem in Logbook
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A short, clear summary of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact steps to reproduce the behavior.
      placeholder: |
        1. Run ...
        2. Execute ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include OS, Node version, pnpm version, and command used.
      placeholder: |
        OS:
        Node:
        pnpm:
        Command:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or output
      description: Paste stack traces, CLI output, or screenshots if useful.
